### ISSUE TITLE
Advanced Navigation: odd display of end-of-loop page

### ISSUE THREAD

**Issue by normon66** [CCALI/a2jauthor#246] opened 2021-12-14 18:14 UTC
If a loop contains a page at the end of each iteration, such as the "Are there any more..." page below (first image), it displays oddly in the Navigation Panel. Rather than "Step 3, Q9" being highlighted at the end of the second iteration, it actually highlights "Step 3, Q5", that same page at the end of the first iteration (second image).

BH UPDATE: After tinkering a bit, I discovered that the "Are there any more..." page did not have a Counting Variable assigned to it, but if I assign the same Counting Variable as was used in the rest of the loop, it works as expected. I think that my initial observation comes down to a legacy navigation bug that I will tag here - stay tuned.

![image](https://user-images.githubusercontent.com/32527754/146054584-0fb19f15-de5c-40d5-aa5d-7d8e45cd969b.png)

![image](https://user-images.githubusercontent.com/32527754/146055974-e84d9c32-518e-405f-8e9a-2a26fb9f4f5e.png)

**Comment by janebitovi** [comment] 2021-12-15 16:44
If there's no loop counter, you can only visit the page once, so it would go back to the previous instance instead of creating a new one

Pretty sure everything is working as intended here but please let me know if there's more to it or if there's a confusing author expectation to address

**Comment by JessicaFrank** [comment] 2021-12-15 17:05
Mine is displaying as expected. 
![image](https://user-images.githubusercontent.com/7662028/146231672-cec4c492-f4ee-4ac5-8ff1-6ec2b617f600.png)

**Comment by normon66** [comment] 2021-12-15 19:06
@JessicaFrank - the "#3" at the end tells me that your repeated page appears within the loop itself (meaning it has a Counting Variable assigned). 
If it's _only_ a question asking if there are more, it doesn't need to be "in" the loop (and doesn't need a Counting Variable), which is when you'd see the behavior I initially noticed.

As @janebitovi noted, it is working as expected, but depending on how an author designs the loop, it could be confusing or look wrong to a user.

**Comment by JessicaFrank** [comment] 2021-12-15 19:11
Thanks for the update @normon66

**Comment by JessicaFrank** [comment] 2021-12-17 15:17
As I understand this issue: This only happens if the author has a "Do you want to add more?" question that is part of the loop, because it gets asked at the end of every iteration, but that the author does not tag as being in a loop by including the counting variable on that page. 

Technically it works in that the end user can move through the loop as expected, but it causes an odd display in the advanced navigation because A2J Author doesn't know this page is supposed to be visited multiple times (because it does not have a repeating variable counter associated with the page). 

I think this one comes down to author training. If a page is meant to be part of a repeat loop, like the "Any More" pages, it needs to be tagged with the counting variable. That's the mechanism the Advanced Nav code relies on to correctly put the page in order for the end user. 

So it might have been allowed in older instances of A2J Author, but we need to be stricter here. 

Please add anything to this ticket if my above assumptions are incorrect. But I'm closing this ticket for now.

**Closed as completed by JessicaFrank** 2021-12-17 15:17 UTC
Labels: bug
